Revert "Do not send email to template users"
This reverts commit 521420587c18163c55c790a2f5241489260cea38.

is_template is not defined on stable version yet:
"NoMethodError: undefined method `is_template?'"