rails3: fix conflict with two activated plugins that has extensions.
Steps to reproduce:
  - Enable vote plugin;
  - Enable work_assignment plugin;
  - Create an UploadedFile;
  - When remove the created UploadedFile: NoMethodError: undefined method `association_class' for nil:NilClass